config/routes.rb
Tutelage2::Application.routes.draw do
  get "sessions/new"

  resources :posts

  resources :users
  
  root :to => 'pages#index'
  
  
  resources :sessions, :only => [:new, :create, :destroy]

    match '/signup',  :to => 'users#new'
    match '/signin',  :to => 'sessions#new'
    match '/signout', :to => 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor   :password
  attr_accessible :name, :email, :password, :password_confirmation
  
  has_many :posts,    :dependent => :destroy
  
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name,  :presence => true,
                    :length   => { :maximum => 50 }
  validates :email, :presence   => true,
                    :format     => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..40 }

  before_save :encrypt_password
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
      user = find_by_email(email)
      if user.nil?
        nil
      elsif user.has_password?(submitted_password)
        user
      end
    end
    
    def self.authenticate_with_salt(id, cookie_salt)
        user = find_by_id(id)
        (user && user.salt == cookie_salt) ? user : nil
      end
      
  
    private

        def encrypt_password
          self.salt = make_salt if new_record?
          self.encrypted_password = encrypt(password)
        end

        def encrypt(string)
          secure_hash("#{salt}--#{string}")
        end

        def make_salt
          secure_hash("#{Time.now.utc}--#{password}")
        end

        def secure_hash(string)
          Digest::SHA2.hexdigest(string)
        end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate, :only => [:index, :edit, :update,:destroy]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user,   :only => :destroy
  
  def index
    
    @title = "All users"
       @users = User.all
    
  end

  def show
    
    @user = User.find(params[:id])
    @title = @user.name
   # @posts = @user.posts.paginate(:page => params[:page])
    
  end
      
  def new
    
    if signed_in?
      
      redirect_to current_user
      
    else
      
      @user = User.new
      @title = "Sign up"
      
    end
    
  end

  def create

    if signed_in?
      
      redirect_to(root_path)
      
    else
      
      @user = User.new(params[:user])
      
      if @user.save
        sign_in @user 
        flash[:success] = "Welcome to the Sample App!"
        redirect_to @user
      else
        @title = "Sign up"
        render 'new'
      end
      
    end
    
  end

  def edit
    @title = "Edit user"
  end

  def update
    
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
    
  end

  def destroy
    
    destroyUser = User.find(params[:id])
    
    if(current_user.admin? && destroyUser == current_user)
      flash[:error] = "An admin user must be deleted by another user"
    else
      destroyUser.destroy
      flash[:success] = "User destroyed."
    end
    
    redirect_to users_path   
       
  end
    
  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
          
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<li>
	<%= link_to user.name, user %>
	<% if current_user.admin? %>
  	| <%= link_to "delete", user, :method => :delete, :confirm => "You sure?", :title => "Delete #{user.name}" %>
	<% end %>
</li>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>All users</h1>



<ul class="users">
	<%= render @users %>
</ul>


<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
        <%= @user.name %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>URL</strong>  <%= link_to user_path(@user), @user %>
    </td>
  </tr>
</table>